- hosts: webserver
   tasks:

   - copy:
       src: /etc/yum.repos.d/epel.repo
       dest: /etc/yum.repos.d/epel.repo

   - name: installing httpd software
     package:
       name: "httpd"
       state: present
     
   - name: Installing php software
     package:
       name: "php"
       state: present

   - name: writing your specified content
     copy:
       dest: "/var/www/html/index.php"
       content: "<pre>\n<?php\n\nprint `/usr/sbin/ifconfig`\n\n?>\n</pre>\n"

   - name: Starting sevices
     service:
       name: "httpd"
       state: restarted

   - name: "Stopping firewalld"
     command: systemctl stop firewalld

 - hosts: haproxy
   vars:
           x: "8080"
   tasks: 
      
   - name: Installing haproxy
     package:
       name: "haproxy"
       state: present

   - name: Configuring HAProxy 
     template:
       dest: "/etc/haproxy/haproxy.cfg"
       src: "haproxy.cfg"

   - selinux:
       policy: targeted
       state: permissive 

   - name: "starting haproxy service {{ ansible_facts['default_ipv4']['address'] }}:{{ x }}"
     service:
       name: "haproxy"
       state: restarted       

   - name: "Stopping firewalld"
     command: systemctl stop firewalld
